# default(모든 프로필 공통 설정)
spring:
  cloud:
    compatibility-verifier:
      enabled: false # cloud 버전이랑 boot버전이랑 안맞대서 빌드 실패하여 추가
  application:
    name: board-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
debug: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /board/swagger
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
server:
  port: 10833

---
spring:
  profiles:
    active: local #local
---
spring:
  profiles:
    active: prod #production
---
spring:
  profiles:
    active: stg #stage